### ISSUE TITLE
Packaging Question

### ISSUE THREAD

**Issue by mole99** [klayoutmatthias/sky130A_el#1]
Hi Matthias! I have a question about this repository :)

When I create a new package using the technology template in KLayout, I get a package with a `tech/` subfolder where I can put all of the files.

But isn't this repository also a technology package? Shouldn't there be a `tech/` folder then?

Thanks!
Leo

**Comment by klayoutmatthias** [comment]
Hi Leo,

KLayout acually looks for the ".lyt" files to find technologies. The location of this file is the default "base path" of that technology - i.e. where it looks up the companion files like ".lyp" etc. Specifically, if KLayout finds a "macros", "pymacros", "ruby" or "python" folder next to the "*.lyt" file, it will associate the scripts there with that technology.

KLayout looks *recursively* for ".lyt" files here:

```
$KLAYOUT_PATH/tech
$KLAYOUT_HOME/tech
$KLAYOUT_HOME/salt/<package names>  (without 'tech')
```

So assume you create a package "my_package", it will be installed in

```
$KLAYOUT_HOME/salt/my_package
```

When you add a ".lyt" file, e.g. "my.lyt", at the package top level and a "macros" folder with one macro:

```
$KLAYOUT_HOME/salt/my_package/macros/macro.lym
$KLAYOUT_HOME/salt/my_package/my.lyt
```

KLayout will find the technology there and associate "macro.lym" with that technology.

You can also put "my.lyt" in any folder, i.e. "tech":

```
$KLAYOUT_HOME/salt/my_package/macros/macro.lym
$KLAYOUT_HOME/salt/my_package/tech/my.lyt
```

In that case "macro.lym" will *not* be associated with the technology, but if you add another macro, like this:

```
$KLAYOUT_HOME/salt/my_package/macros/macro.lym
$KLAYOUT_HOME/salt/my_package/tech/macros/macro2.lym
$KLAYOUT_HOME/salt/my_package/tech/my.lyt
```

then "macro2.lym" is associated with the technology, while "macro.lym" is not.

So eventually, the recommendation is to use a folder, i.e. "tech" to separate things that are technology related and others that are not. But you can also create a pure technology package and put ".lyt" and package top level.

Currently, it does not make a huge difference whether a macro is associated with a technology or not, but that may change. 

Hope that helps.

Matthias

**Comment by mole99** [comment]
Thanks a lot Matthias! That clears things up :)

Eventually I would like to register a package for https://github.com/efabless/sky130_klayout_pdk
That's why I was asking!

Closing this issue now.
